// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Area struct {
	ID       int64
	Title    string
	Status   sql.NullString
	Archived sql.NullBool
}

type BridgeNote struct {
	NoteID       sql.NullInt64
	ParentCat    sql.NullInt64
	ParentTaskID sql.NullInt64
	ParentAreaID sql.NullInt64
}

type Note struct {
	ID    int64
	Title string
	Path  string
}

type Task struct {
	ID        int64
	Title     string
	Priority  sql.NullString
	Status    sql.NullString
	Archived  sql.NullBool
	CreatedAt sql.NullTime
	LastMod   sql.NullTime
	DueDate   sql.NullTime
	AreaID    sql.NullInt64
}
